ERROR 2024-03-04 13:49:10,246  101 The field 'organization_id' was declared on serializer CreateQuizSerializer, but has not been included in the 'fields' option.
ERROR 2024-03-04 13:49:45,566  101 The field 'organization_id' was declared on serializer CreateQuizSerializer, but has not been included in the 'fields' option.
ERROR 2024-03-04 15:16:35,049  160 Invalid field name(tt) pass.
ERROR | 2024-03-04 16:12:25,147| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-04 16:12:25,147| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-04 18:27:34,221| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:10:35,055| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:11:42,043| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:13:42,388| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:13:56,881| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:15:11,981| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-05 10:16:08,466| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-05 10:17:15,187| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | cannot access local variable 'errors' where it is not associated with a value
ERROR | 2024-03-05 11:38:54,440| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 68 | Invalid JSON data. Extra data: line 74 column 1 (char 402)
ERROR | 2024-03-06 10:19:39,978| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:20:35,424| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:20:35,425| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:20:35,439| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'correctOptions' was declared on serializer GETAllQuizQuestionsSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-06 10:21:27,362| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:27,362| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:21:27,377| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'value'
ERROR | 2024-03-06 10:21:30,674| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:30,675| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:21:30,681| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'value'
ERROR | 2024-03-06 10:21:50,954| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:50,956| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:22:32,425| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:22:32,426| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:22:32,438| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'id'
ERROR | 2024-03-06 10:22:59,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:22:59,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:23:44,040| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:23:48,722| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:24:50,612| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:24:50,613| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:28:52,953| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:28:52,954| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:29:42,807| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:29:42,808| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:40:14,631| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:40:14,632| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:42:00,283| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:42:00,283| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:47:46,709| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:47:46,710| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:50:50,926| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 11:51:19,328| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:51:19,329| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:15:08,015| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:15:08,017| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:19:23,114| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:19:23,114| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:19:40,048| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:19:40,049| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:25:29,828| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:25:29,828| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:35:15,771| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:35:15,771| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:47:29,401| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:47:29,402| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:18,798| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:41:18,798| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:18,844| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'correct_answer' was declared on serializer GETAllQuizQuestionsSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-06 13:41:42,039| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:41:42,040| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:42,072| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'GETAllQuizQuestionsSerializer' object has no attribute 'get_correct_answer'
ERROR | 2024-03-06 13:42:32,404| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:32,404| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:42:53,866| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:53,866| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:42:59,456| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:59,458| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:44:12,581| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:44:12,581| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 14:13:19,280| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 14:13:19,282| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 14:13:19,292| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizQuestions' object has no attribute 'order'
ERROR | 2024-03-06 14:17:28,819| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 14:17:28,819| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 19:14:18,908| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-06 19:14:21,211| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-06 19:14:24,440| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-07 10:10:34,641| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-07 10:10:41,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-07 14:53:05,274| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-07 14:53:05,274| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-07 14:54:10,257| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-07 14:54:10,257| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-07 14:57:20,945| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-07 17:04:58,013| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:05:23,714| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:06:28,984| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:07:43,256| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:09:47,579| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:13:15,084| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:13:54,366| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:15:33,844| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:27:55,878| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'appen'
ERROR | 2024-03-07 17:28:40,640| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 17:29:35,631| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 17:33:02,072| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 18:07:45,841| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'strip'
ERROR | 2024-03-07 18:08:22,578| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'strip'
ERROR | 2024-03-07 18:08:55,121| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:13:06,566| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:13:55,044| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:33:21,382| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'str' object has no attribute 'capital'
ERROR | 2024-03-08 10:12:02,499| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-08 10:12:06,598| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-08 12:14:18,084| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | rest_framework/api.html
ERROR | 2024-03-08 12:50:41,788| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'username' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:50:57,214| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:50:58,265| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:50:59,017| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:53:08,781| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'username' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:58:19,106| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 13:04:47,896| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | '>' not supported between instances of 'QuerySet' and 'int'
ERROR | 2024-03-08 13:29:25,667| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | QuizEnrollment() got unexpected keyword arguments: 'staus'
ERROR | 2024-03-08 13:54:49,112| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | CharField.__init__() takes 1 positional argument but 2 were given
ERROR | 2024-03-08 13:56:27,574| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | CharField.__init__() takes 1 positional argument but 2 were given
ERROR | 2024-03-08 18:17:10,522| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:17:12,289| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:17:13,344| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:17:14,284| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:20:38,682| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'int' object is not subscriptable
ERROR | 2024-03-08 18:22:34,928| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'int' object is not subscriptable
ERROR | 2024-03-08 18:48:07,926| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | cannot access local variable 'errors' where it is not associated with a value
ERROR | 2024-03-08 18:59:59,925| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 68 | Invalid JSON data. Expecting property name enclosed in double quotes: line 8 column 1 (char 83)
ERROR | 2024-03-11 13:24:42,751| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-11 13:24:49,589| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-11 14:09:44,965| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-11 14:11:28,255| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-11 14:12:37,429| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-11 15:24:10,175| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phonenumbers' was declared on serializer UserSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-11 15:54:11,292| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'queries'
ERROR | 2024-03-11 16:36:06,936| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-12 10:48:54,534| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-12 10:51:04,348| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-12 12:25:06,529| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `total_questionsorganization_id` is not valid for model `Quiz`.
ERROR | 2024-03-12 12:25:31,683| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `total_questions` is not valid for model `Quiz`.
ERROR | 2024-03-12 12:25:33,500| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `total_questions` is not valid for model `Quiz`.
ERROR | 2024-03-12 12:28:15,937| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'total_question' was declared on serializer GETAllQuizSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-12 12:28:17,166| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'total_question' was declared on serializer GETAllQuizSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-12 12:34:53,331| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The annotation 'totalQuestions' conflicts with a field on the model.
ERROR | 2024-03-12 12:56:15,484| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | type object 'bool' has no attribute 'split'
ERROR | 2024-03-12 12:57:17,996| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected parent FilterSet 'Quiz_Api.quiz.filters.QuizFilter' to have a '.filter_total_questions_gt()' method.
ERROR | 2024-03-13 11:10:23,990| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-13 11:10:23,991| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-13 11:13:18,843| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-13 11:13:18,844| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-13 11:14:15,453| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-13 11:14:15,454| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-13 11:14:38,803| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-19 10:10:51,012| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-19 13:10:51,125| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-19 13:11:05,276| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'userId' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-19 13:15:44,302| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'user_id'
ERROR | 2024-03-19 13:16:46,529| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:20:11,317| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:21:12,728| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:23:53,437| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:27:05,282| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:29:47,070| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:33:13,163| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:35:37,602| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:36:48,268| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:40:46,607| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:42:41,663| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:43:19,080| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:43:49,437| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:44:37,578| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:46:45,516| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:49:12,816| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:56:13,255| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'user_id_id' cannot be null")
ERROR | 2024-03-19 13:56:50,793| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'quiz_id_id' cannot be null")
ERROR | 2024-03-19 14:08:57,037| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-19 16:58:14,645| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | .validate() should return the validated data
ERROR | 2024-03-19 17:14:49,377| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | .validate() should return the validated data
ERROR | 2024-03-19 17:15:32,448| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | .validate() should return the validated data
ERROR | 2024-03-19 17:16:21,378| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | .validate() should return the validated data
ERROR | 2024-03-19 17:16:41,750| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | .validate() should return the validated data
ERROR | 2024-03-19 17:17:29,367| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | .validate() should return the validated data
ERROR | 2024-03-19 17:17:57,801| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got a `TypeError` when calling `QuizPlay.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `QuizPlay.objects.create()`. You may need to make the field read-only, or override the CreateQuizPlaySerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: QuizPlay() got unexpected keyword arguments: 'optionId'

ERROR | 2024-03-19 17:20:15,646| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got a `TypeError` when calling `QuizPlay.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `QuizPlay.objects.create()`. You may need to make the field read-only, or override the CreateQuizPlaySerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: QuizPlay() got unexpected keyword arguments: 'optionId'

ERROR | 2024-03-19 17:23:50,654| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got a `TypeError` when calling `QuizPlay.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `QuizPlay.objects.create()`. You may need to make the field read-only, or override the CreateQuizPlaySerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: QuizPlay() got unexpected keyword arguments: 'optionId'

ERROR | 2024-03-19 17:52:24,677| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got a `TypeError` when calling `QuizPlay.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `QuizPlay.objects.create()`. You may need to make the field read-only, or override the CreateQuizPlaySerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: QuizPlay() got unexpected keyword arguments: 'optionId'

ERROR | 2024-03-19 17:56:26,103| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got a `TypeError` when calling `QuizPlay.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `QuizPlay.objects.create()`. You may need to make the field read-only, or override the CreateQuizPlaySerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vs123\OneDrive\Desktop\quiz\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: QuizPlay() got unexpected keyword arguments: 'optionId'

ERROR | 2024-03-20 10:05:07,577| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-20 10:10:38,625| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-20 10:12:07,268| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizQuestions' object has no attribute 'count'
ERROR | 2024-03-20 10:12:30,434| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | type object 'QuizQuestions' has no attribute 'filter'
ERROR | 2024-03-20 10:12:31,707| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | type object 'QuizQuestions' has no attribute 'filter'
ERROR | 2024-03-20 10:12:48,399| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field 'id' expected a number but got <QuizQuestions: QuizQuestions object (49)>.
ERROR | 2024-03-20 10:17:09,856| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field 'id' expected a number but got <QuizQuestions: QuizQuestions object (49)>.
ERROR | 2024-03-20 11:45:12,290| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Manager isn't accessible via QuizQuestions instances
ERROR | 2024-03-20 11:45:34,932| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizQuestions' object has no attribute 'answers'
ERROR | 2024-03-20 11:53:51,778| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'values_listt'
ERROR | 2024-03-20 12:56:29,917| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | object of type 'int' has no len()
ERROR | 2024-03-20 14:36:03,881| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'User' object has no attribute 'options'
ERROR | 2024-03-20 14:36:41,370| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | `create()` did not return an object instance.
ERROR | 2024-03-20 14:58:34,957| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | '>' not supported between instances of 'QuerySet' and 'int'
ERROR | 2024-03-20 16:50:37,351| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | `create()` did not return an object instance.
ERROR | 2024-03-20 16:55:37,340| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'RelatedManager' object has no attribute 'incorrectAnswer'
ERROR | 2024-03-20 17:00:33,666| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'RelatedManager' object has no attribute 'correctAnswer'
ERROR | 2024-03-20 17:07:07,365| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | QuizEnrollment() got unexpected keyword arguments: 'userId', 'quizId'
ERROR | 2024-03-20 17:54:06,449| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'first'
ERROR | 2024-03-21 14:15:48,728| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `user` is not valid for model `QuizEnrollment`.
ERROR | 2024-03-21 14:17:05,462| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `userId` is not valid for model `QuizEnrollment`.
ERROR | 2024-03-21 14:17:08,364| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `userId` is not valid for model `QuizEnrollment`.
ERROR | 2024-03-21 14:22:29,564| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `user_id__name` is not valid for model `QuizEnrollment`.
ERROR | 2024-03-21 14:29:30,250| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'title' was declared on serializer GETAllQuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-21 14:30:12,273| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'GETAllQuizEnrolmentSerializer' object has no attribute 'get_title'
ERROR | 2024-03-21 14:30:13,249| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'GETAllQuizEnrolmentSerializer' object has no attribute 'get_title'
ERROR | 2024-03-21 16:39:25,671| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'strftime'
ERROR | 2024-03-22 10:14:06,363| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-22 10:14:35,357| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-22 10:28:17,908| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-22 10:28:55,848| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR | 2024-03-22 10:30:27,262| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR | 2024-03-22 10:31:45,330| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR | 2024-03-22 10:32:37,788| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR | 2024-03-22 10:34:43,932| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'save'
ERROR | 2024-03-22 12:05:40,357| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | rest_framework/api.html
ERROR | 2024-03-22 12:07:07,180| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | rest_framework/api.html
ERROR | 2024-03-22 13:07:56,302| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | rest_framework/api.html
ERROR | 2024-03-22 13:11:26,633| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-22 13:11:26,633| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-22 13:11:41,388| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-22 13:11:41,389| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-22 13:13:01,873| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-22 13:13:01,873| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-26 10:02:12,578| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-26 10:06:17,763| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-26 10:06:17,763| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-26 10:07:21,805| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-26 10:07:21,807| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-26 10:18:14,984| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-26 10:18:19,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-26 11:53:50,114| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-26 11:53:50,115| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-26 13:40:23,651| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | GETAllQuestionsByQuizIdAndUserId.filter_queryset() missing 1 required positional argument: 'userId'
ERROR | 2024-03-26 13:44:37,912| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 13:44:46,018| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 13:47:55,368| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 13:50:17,317| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 13:50:33,264| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 14:12:21,172| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 14:17:25,112| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 14:18:23,888| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 14:32:21,754| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 14:33:58,108| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'F' object has no attribute 'filter'
ERROR | 2024-03-26 15:04:09,527| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 15:04:10,774| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1242, 'Subquery returns more than 1 row')
ERROR | 2024-03-26 15:04:43,913| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'int' object is not subscriptable
ERROR | 2024-03-26 15:04:45,312| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'int' object is not subscriptable
ERROR | 2024-03-26 16:24:11,028| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'GETAllQuizQuestionsByQuizIdAndUserIdSerializer' object has no attribute 'get_selected_option'
ERROR | 2024-03-26 16:27:14,008| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'GETAllQuizQuestionsByQuizIdAndUserIdSerializer' object has no attribute 'get_selected_option'
ERROR | 2024-03-26 17:04:20,560| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'str' object has no attribute 'in_'
ERROR | 2024-03-27 10:27:17,083| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-27 10:59:10,644| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-27 11:01:13,019| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'status' cannot be null")
ERROR | 2024-03-27 11:03:29,029| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | (1048, "Column 'status' cannot be null")
ERROR | 2024-03-27 12:03:56,058| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:03:56,058| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:04:56,273| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:04:56,273| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:05:07,339| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:05:07,339| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:05:08,799| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:05:08,799| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:05:10,075| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:05:10,076| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:05:11,510| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:05:11,511| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:05:12,763| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:05:12,764| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:05:14,382| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 68 | str(e)
ERROR | 2024-03-27 12:05:14,382| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 74 | str(e)
ERROR | 2024-03-27 12:16:55,850| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-27 12:18:56,268| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'exist'
ERROR | 2024-03-28 10:18:40,741| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-28 10:19:10,727| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `startDate` on serializer `GETAllQuizEnrolmentSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuizEnrollment` instance.
Original exception text was: 'QuizEnrollment' object has no attribute 'quizId__startDate'.
ERROR | 2024-03-28 10:19:54,395| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `startDate` on serializer `GETAllQuizEnrolmentSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuizEnrollment` instance.
Original exception text was: 'QuizEnrollment' object has no attribute 'quiz_id__startDate'.
ERROR | 2024-03-28 10:24:52,729| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'startDate'
ERROR | 2024-03-28 10:25:32,057| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'startDate'
ERROR | 2024-03-28 10:26:48,960| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'startDate'
ERROR | 2024-03-28 10:27:47,827| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'quizId'
ERROR | 2024-03-28 10:27:50,316| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'quizId'
ERROR | 2024-03-28 10:29:56,177| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'startDate'
ERROR | 2024-03-28 10:31:01,890| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizEnrollment' object has no attribute 'startDate'
ERROR | 2024-03-28 10:56:51,264| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'order_by'
ERROR | 2024-03-28 11:46:01,751| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'startDate' was declared on serializer GETAllQuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-28 11:52:57,158| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `price` is not valid for model `Quiz`.
ERROR | 2024-03-28 12:10:13,529| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected a `date`, but got a `datetime`. Refusing to coerce, as this may mean losing timezone information. Use a custom read-only field and deal with timezone issues explicitly.
ERROR | 2024-03-28 13:24:45,400| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'DeferredAttribute' object is not iterable
ERROR | 2024-03-28 14:02:17,450| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'Options' object has no attribute 'get_all_field_names'
ERROR | 2024-03-28 14:10:19,683| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'Options' object has no attribute 'get_all_field_names'
ERROR | 2024-03-28 14:17:35,116| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'label'
ERROR | 2024-03-28 17:25:28,119| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizDetailsSerializer' object has no attribute 'get_total_questions'
ERROR | 2024-03-28 18:19:26,229| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'LocMemCache' object has no attribute 'keys'
ERROR | 2024-03-28 18:20:20,619| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'LocMemCache' object has no attribute 'items'
ERROR | 2024-03-28 18:20:50,493| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'LocMemCache' object has no attribute 'key'
ERROR | 2024-03-28 18:22:00,841| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'LocMemCache' object has no attribute 'keys'
ERROR | 2024-03-28 18:22:43,328| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'LocMemCache' object has no attribute 'keys'
ERROR | 2024-03-28 18:44:10,672| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizDetailsSerializer' object has no attribute 'get_resultDate'
ERROR | 2024-03-28 18:44:12,775| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizDetailsSerializer' object has no attribute 'get_resultDate'
ERROR | 2024-03-29 10:05:46,391| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-29 10:06:00,665| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-29 11:52:31,079| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-29 12:03:51,165| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field.__init__() got an unexpected keyword argument 'default'
ERROR | 2024-03-29 12:04:38,060| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | ['“e” value has an invalid date format. It must be in YYYY-MM-DD format.']
ERROR | 2024-03-29 12:44:00,014| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected parent FilterSet 'Quiz_Api.enroll_and_result.filters.QuizEnrollmentFilter' to have a '.filter_order_by()' method.
ERROR | 2024-03-29 16:07:37,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected parent FilterSet 'Quiz_Api.enroll_and_result.filters.QuizEnrollmentFilter' to have a '.filter_quiz_endDate__lte()' method.
ERROR | 2024-03-29 16:22:35,514| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected parent FilterSet 'Quiz_Api.enroll_and_result.filters.QuizEnrollmentFilter' to have a '.filter_quiz_endDate__lte()' method.
ERROR | 2024-03-30 10:06:57,104| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-30 10:07:04,935| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-30 16:05:56,693| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-01 10:28:16,954| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-01 10:28:21,562| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-01 11:39:59,858| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-02 14:38:20,941| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-02 15:51:37,509| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'Quiz' object has no attribute 'strftime'
ERROR | 2024-04-02 15:52:44,889| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'Quiz' object has no attribute 'strftime'
ERROR | 2024-04-02 15:52:46,490| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'Quiz' object has no attribute 'strftime'
ERROR | 2024-04-02 15:53:13,946| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | '>=' not supported between instances of 'datetime.datetime' and 'str'
ERROR | 2024-04-02 15:53:55,843| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | can't compare datetime.datetime to datetime.date
ERROR | 2024-04-02 17:20:53,732| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field 'id' expected a number but got <Quiz: Quiz object (1)>.
ERROR | 2024-04-03 10:08:23,884| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-03 10:09:43,572| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-03 23:18:27,930| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-03 23:19:17,210| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-03 23:19:17,211| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-03 23:21:42,541| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-03 23:21:42,543| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-03 23:22:12,633| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-03 23:22:12,633| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 11:22:45,584| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | cannot access local variable 'queryset' where it is not associated with a value
ERROR | 2024-04-04 11:23:27,392| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'order_by'
ERROR | 2024-04-04 11:23:59,592| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'order_by'
ERROR | 2024-04-04 11:25:54,104| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizDetailsSerializer' object has no attribute 'get_totalQuestions'
ERROR | 2024-04-04 11:26:26,893| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizDetailsSerializer' object has no attribute 'get_totalQuestions'
ERROR | 2024-04-04 11:27:29,505| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `totalQuestions` on serializer `QuizDetailsSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Quiz` instance.
Original exception text was: 'Quiz' object has no attribute 'totalQuestions'.
ERROR | 2024-04-04 11:29:35,424| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `totalQuestions` on serializer `QuizDetailsSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Quiz` instance.
Original exception text was: 'Quiz' object has no attribute 'totalQuestions'.
ERROR | 2024-04-04 11:35:18,735| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `totalQuestions` on serializer `QuizDetailsSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `Quiz` instance.
Original exception text was: 'Quiz' object has no attribute 'totalQuestions'.
ERROR | 2024-04-04 11:42:12,237| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-04 12:08:39,716| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:08:39,717| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:18:29,762| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:18:29,763| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:18:29,774| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | It is redundant to specify `source='question'` on field 'GETQuestionSerializer' in serializer 'GETAllQuizQuestionsSerializer', because it is the same as the field name. Remove the `source` keyword argument.
ERROR | 2024-04-04 12:18:59,794| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:18:59,794| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:18:59,810| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:19:23,928| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:19:23,928| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:19:23,939| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:22:33,873| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:22:33,873| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:22:33,888| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `question` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:24:25,534| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:24:25,534| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:24:25,545| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `questions` on serializer `GETAllQuizQuestionsSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuizQuestions` instance.
Original exception text was: 'QuizQuestions' object has no attribute 'questions'.
ERROR | 2024-04-04 12:26:08,630| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:26:08,631| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:26:08,650| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:30:35,447| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:30:35,448| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:30:35,468| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | argument of type 'builtin_function_or_method' is not iterable
ERROR | 2024-04-04 12:32:24,324| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:32:24,324| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:32:24,335| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | argument of type 'builtin_function_or_method' is not iterable
ERROR | 2024-04-04 12:32:55,832| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:32:55,832| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:32:55,842| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `int` instance.
Original exception text was: 'int' object has no attribute 'question'.
ERROR | 2024-04-04 12:33:21,557| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:33:21,557| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:33:21,569| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:45:14,481| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:45:14,482| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:45:14,498| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:45:47,668| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:45:47,668| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:45:47,677| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question__question'.
ERROR | 2024-04-04 12:46:27,877| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:46:27,877| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:46:27,892| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `question` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:47:33,747| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:47:33,749| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:47:33,762| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `question` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 12:49:34,243| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:49:34,244| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:49:34,252| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `option` on serializer `GETAnswerSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `RelatedManager` instance.
Original exception text was: 'RelatedManager' object has no attribute 'option'.
ERROR | 2024-04-04 12:50:40,324| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:50:40,324| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 12:53:57,845| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:56:28,252| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 12:57:51,655| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:01:23,083| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:01:50,559| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:02:49,284| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:03:08,571| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:04:13,596| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:05:10,132| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:05:10,133| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:07:47,132| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:07:47,133| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:08:54,643| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:08:54,643| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:10:33,927| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:10:33,928| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:11:24,713| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:11:24,713| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:13:20,176| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:13:20,176| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:13:20,184| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `text` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'question'.
ERROR | 2024-04-04 13:14:46,324| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:14:46,324| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:14:46,335| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `type` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'type'.
ERROR | 2024-04-04 13:15:13,031| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:15:13,031| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:15:13,042| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `type` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'type'.
ERROR | 2024-04-04 13:15:27,421| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:15:27,421| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:15:27,436| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Got AttributeError when attempting to get a value for field `type` on serializer `GETQuestionSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'type'.
ERROR | 2024-04-04 13:16:14,420| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:16:14,420| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:18:35,944| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:18:35,944| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:18:46,046| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:18:46,046| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:20:19,737| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:20:19,737| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:27:46,731| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:27:46,733| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:44:55,245| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:44:55,245| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:47:57,439| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:47:57,439| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:47:57,450| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizQuestions' object has no attribute 'correct_answer'
ERROR | 2024-04-04 13:48:19,695| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:48:19,696| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 13:50:10,496| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 13:50:10,496| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:11:03,267| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:11:03,267| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:11:37,693| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:11:37,693| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:12:08,585| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:12:08,586| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:13:40,641| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:13:40,641| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:14:37,821| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:14:37,821| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:15:26,390| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:15:26,391| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:16:58,871| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:16:58,871| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:17:44,863| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:17:44,864| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:18:23,116| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:18:23,118| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:18:33,442| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:18:33,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:18:45,614| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:18:45,614| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:18:47,402| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:18:47,403| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:18:49,874| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:18:49,874| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:18:58,537| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:18:58,537| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:00,264| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:00,264| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:01,733| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:01,734| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:02,986| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:02,986| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:04,169| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:04,169| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:05,429| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:05,430| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:06,527| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:06,527| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:07,692| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:07,693| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:10,118| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:10,119| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:11,616| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:11,616| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:12,907| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:12,908| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:14,005| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:14,006| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:15,201| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:15,201| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:16,301| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:16,301| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:17,460| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:17,460| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:18,703| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:18,704| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:19,941| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:19,941| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:21,096| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:21,096| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:22,213| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:22,213| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:23,337| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:23,338| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:24,649| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:24,649| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:26,491| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:26,492| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:27,358| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:27,359| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:28,640| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:28,640| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:29,887| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:29,888| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:31,223| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:31,223| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:19:32,340| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:19:32,341| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:20:08,535| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:20:08,535| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:20:23,058| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:20:23,058| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:22:36,629| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 14:22:36,630| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 92 | str(e)
ERROR | 2024-04-04 14:22:51,203| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 86 | str(e)
ERROR | 2024-04-04 15:00:04,957| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | This queryset contains a reference to an outer query and may only be used in a subquery.
ERROR | 2024-04-04 15:11:46,235| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Object of type QuizPlay is not JSON serializable
ERROR | 2024-04-04 15:13:49,582| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Object of type QuizPlay is not JSON serializable
ERROR | 2024-04-04 15:15:09,597| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Object of type QuizPlay is not JSON serializable
ERROR | 2024-04-04 15:35:39,424| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Prefetch querysets cannot use raw(), values(), and values_list().
ERROR | 2024-04-04 15:37:51,146| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Prefetch querysets cannot use raw(), values(), and values_list().
ERROR | 2024-04-04 15:49:38,084| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'user_id'
ERROR | 2024-04-05 15:23:37,556| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-05 17:23:36,926| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `score` is not valid for model `QuizEnrollment`.
ERROR | 2024-04-05 17:25:59,870| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-04-05 17:29:04,977| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'Quiz' object has no attribute 'questions'
