ERROR 2024-03-04 13:49:10,246  101 The field 'organization_id' was declared on serializer CreateQuizSerializer, but has not been included in the 'fields' option.
ERROR 2024-03-04 13:49:45,566  101 The field 'organization_id' was declared on serializer CreateQuizSerializer, but has not been included in the 'fields' option.
ERROR 2024-03-04 15:16:35,049  160 Invalid field name(tt) pass.
ERROR | 2024-03-04 16:12:25,147| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-04 16:12:25,147| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-04 18:27:34,221| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:10:35,055| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:11:42,043| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:13:42,388| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:13:56,881| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:15:11,981| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-05 10:16:08,466| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-05 10:17:15,187| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | cannot access local variable 'errors' where it is not associated with a value
ERROR | 2024-03-05 11:38:54,440| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 68 | Invalid JSON data. Extra data: line 74 column 1 (char 402)
ERROR | 2024-03-06 10:19:39,978| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:20:35,424| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:20:35,425| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:20:35,439| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'correctOptions' was declared on serializer GETAllQuizQuestionsSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-06 10:21:27,362| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:27,362| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:21:27,377| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'value'
ERROR | 2024-03-06 10:21:30,674| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:30,675| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:21:30,681| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'value'
ERROR | 2024-03-06 10:21:50,954| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:50,956| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:22:32,425| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:22:32,426| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:22:32,438| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'id'
ERROR | 2024-03-06 10:22:59,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:22:59,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:23:44,040| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:23:48,722| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:24:50,612| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:24:50,613| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:28:52,953| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:28:52,954| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:29:42,807| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:29:42,808| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:40:14,631| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:40:14,632| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:42:00,283| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:42:00,283| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:47:46,709| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:47:46,710| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:50:50,926| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 11:51:19,328| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:51:19,329| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:15:08,015| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:15:08,017| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:19:23,114| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:19:23,114| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:19:40,048| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:19:40,049| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:25:29,828| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:25:29,828| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:35:15,771| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:35:15,771| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:47:29,401| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:47:29,402| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:18,798| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:41:18,798| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:18,844| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'correct_answer' was declared on serializer GETAllQuizQuestionsSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-06 13:41:42,039| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:41:42,040| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:42,072| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'GETAllQuizQuestionsSerializer' object has no attribute 'get_correct_answer'
ERROR | 2024-03-06 13:42:32,404| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:32,404| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:42:53,866| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:53,866| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:42:59,456| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:59,458| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:44:12,581| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:44:12,581| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 14:13:19,280| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 14:13:19,282| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 14:13:19,292| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizQuestions' object has no attribute 'order'
ERROR | 2024-03-06 14:17:28,819| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 14:17:28,819| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 19:14:18,908| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-06 19:14:21,211| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-06 19:14:24,440| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-07 10:10:34,641| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-07 10:10:41,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-07 14:53:05,274| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-07 14:53:05,274| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-07 14:54:10,257| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-07 14:54:10,257| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-07 14:57:20,945| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-07 17:04:58,013| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:05:23,714| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:06:28,984| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:07:43,256| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:09:47,579| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:13:15,084| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:13:54,366| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:15:33,844| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:27:55,878| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'appen'
ERROR | 2024-03-07 17:28:40,640| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 17:29:35,631| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 17:33:02,072| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 18:07:45,841| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'strip'
ERROR | 2024-03-07 18:08:22,578| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'strip'
ERROR | 2024-03-07 18:08:55,121| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:13:06,566| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:13:55,044| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:33:21,382| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'str' object has no attribute 'capital'
ERROR | 2024-03-08 10:12:02,499| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-08 10:12:06,598| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-08 12:14:18,084| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | rest_framework/api.html
ERROR | 2024-03-08 12:50:41,788| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'username' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:50:57,214| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:50:58,265| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:50:59,017| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:53:08,781| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'username' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 12:58:19,106| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phoneNumber' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 13:04:47,896| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | '>' not supported between instances of 'QuerySet' and 'int'
ERROR | 2024-03-08 13:29:25,667| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | QuizEnrollment() got unexpected keyword arguments: 'staus'
ERROR | 2024-03-08 13:54:49,112| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | CharField.__init__() takes 1 positional argument but 2 were given
ERROR | 2024-03-08 13:56:27,574| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | CharField.__init__() takes 1 positional argument but 2 were given
ERROR | 2024-03-08 18:17:10,522| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:17:12,289| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:17:13,344| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:17:14,284| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'user' was declared on serializer QuizEnrolmentSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-08 18:20:38,682| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'int' object is not subscriptable
ERROR | 2024-03-08 18:22:34,928| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'int' object is not subscriptable
ERROR | 2024-03-08 18:48:07,926| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | cannot access local variable 'errors' where it is not associated with a value
ERROR | 2024-03-08 18:59:59,925| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 68 | Invalid JSON data. Expecting property name enclosed in double quotes: line 8 column 1 (char 83)
ERROR | 2024-03-11 13:24:42,751| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-11 13:24:49,589| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-11 14:09:44,965| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-11 14:11:28,255| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-11 14:12:37,429| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-11 15:24:10,175| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'phonenumbers' was declared on serializer UserSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-11 15:54:11,292| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'queries'
ERROR | 2024-03-11 16:36:06,936| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-12 10:48:54,534| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-12 10:51:04,348| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-12 12:25:06,529| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `total_questionsorganization_id` is not valid for model `Quiz`.
ERROR | 2024-03-12 12:25:31,683| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `total_questions` is not valid for model `Quiz`.
ERROR | 2024-03-12 12:25:33,500| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Field name `total_questions` is not valid for model `Quiz`.
ERROR | 2024-03-12 12:28:15,937| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'total_question' was declared on serializer GETAllQuizSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-12 12:28:17,166| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'total_question' was declared on serializer GETAllQuizSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-12 12:34:53,331| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The annotation 'totalQuestions' conflicts with a field on the model.
ERROR | 2024-03-12 12:56:15,484| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | type object 'bool' has no attribute 'split'
ERROR | 2024-03-12 12:57:17,996| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | Expected parent FilterSet 'Quiz_Api.quiz.filters.QuizFilter' to have a '.filter_total_questions_gt()' method.
