ERROR 2024-03-04 13:49:10,246  101 The field 'organization_id' was declared on serializer CreateQuizSerializer, but has not been included in the 'fields' option.
ERROR 2024-03-04 13:49:45,566  101 The field 'organization_id' was declared on serializer CreateQuizSerializer, but has not been included in the 'fields' option.
ERROR 2024-03-04 15:16:35,049  160 Invalid field name(tt) pass.
ERROR | 2024-03-04 16:12:25,147| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-04 16:12:25,147| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-04 18:27:34,221| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:10:35,055| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:11:42,043| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:13:42,388| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:13:56,881| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'quizId'
ERROR | 2024-03-05 10:15:11,981| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-05 10:16:08,466| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'get'
ERROR | 2024-03-05 10:17:15,187| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | cannot access local variable 'errors' where it is not associated with a value
ERROR | 2024-03-05 11:38:54,440| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 68 | Invalid JSON data. Extra data: line 74 column 1 (char 402)
ERROR | 2024-03-06 10:19:39,978| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:20:35,424| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:20:35,425| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:20:35,439| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'correctOptions' was declared on serializer GETAllQuizQuestionsSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-06 10:21:27,362| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:27,362| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:21:27,377| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'value'
ERROR | 2024-03-06 10:21:30,674| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:30,675| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:21:30,681| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuerySet' object has no attribute 'value'
ERROR | 2024-03-06 10:21:50,954| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:21:50,956| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:22:32,425| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:22:32,426| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:22:32,438| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'id'
ERROR | 2024-03-06 10:22:59,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:22:59,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:23:44,040| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:23:48,722| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 10:24:50,612| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:24:50,613| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:28:52,953| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:28:52,954| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 10:29:42,807| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 10:29:42,808| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:40:14,631| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:40:14,632| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:42:00,283| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:42:00,283| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:47:46,709| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:47:46,710| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 11:50:50,926| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-06 11:51:19,328| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 11:51:19,329| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:15:08,015| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:15:08,017| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:19:23,114| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:19:23,114| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:19:40,048| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:19:40,049| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:25:29,828| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:25:29,828| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:35:15,771| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:35:15,771| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 12:47:29,401| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 12:47:29,402| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:18,798| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:41:18,798| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:18,844| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | The field 'correct_answer' was declared on serializer GETAllQuizQuestionsSerializer, but has not been included in the 'fields' option.
ERROR | 2024-03-06 13:41:42,039| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:41:42,040| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:41:42,072| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'GETAllQuizQuestionsSerializer' object has no attribute 'get_correct_answer'
ERROR | 2024-03-06 13:42:32,404| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:32,404| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:42:53,866| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:53,866| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:42:59,456| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:42:59,458| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 13:44:12,581| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 13:44:12,581| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 14:13:19,280| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 14:13:19,282| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 14:13:19,292| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'QuizQuestions' object has no attribute 'order'
ERROR | 2024-03-06 14:17:28,819| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 63 | str(e)
ERROR | 2024-03-06 14:17:28,819| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 69 | str(e)
ERROR | 2024-03-06 19:14:18,908| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-06 19:14:21,211| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-06 19:14:24,440| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-07 10:10:34,641| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-07 10:10:41,443| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: __call__ | line_no: 29 | Invalid URL.
ERROR | 2024-03-07 14:53:05,274| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-07 14:53:05,274| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-07 14:54:10,257| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 66 | str(e)
ERROR | 2024-03-07 14:54:10,257| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\Quiz_Api\add_questions\views.py | func: filter_queryset | line_no: 72 | str(e)
ERROR | 2024-03-07 14:57:20,945| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 
ERROR | 2024-03-07 17:04:58,013| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:05:23,714| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:06:28,984| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:07:43,256| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'list' object has no attribute 'items'
ERROR | 2024-03-07 17:09:47,579| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:13:15,084| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:13:54,366| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:15:33,844| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'correct_answer'
ERROR | 2024-03-07 17:27:55,878| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'appen'
ERROR | 2024-03-07 17:28:40,640| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 17:29:35,631| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 17:33:02,072| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'dict' object has no attribute 'append'
ERROR | 2024-03-07 18:07:45,841| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'strip'
ERROR | 2024-03-07 18:08:22,578| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'strip'
ERROR | 2024-03-07 18:08:55,121| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:13:06,566| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:13:55,044| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'NoneType' object has no attribute 'lower'
ERROR | 2024-03-07 18:33:21,382| path: C:\Users\vs123\OneDrive\Desktop\quiz\JDC\utils\middleware.py | func: process_exception | line_no: 101 | 'str' object has no attribute 'capital'
